// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNSPECIFIED.String() && e.Code == 500
}

func ErrorUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

// 订单
func IsOrderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REVIEWED.String() && e.Code == 409
}

// 订单
func ErrorOrderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_ORDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}

func IsOrderReplied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REPLIED.String() && e.Code == 409
}

func ErrorOrderReplied(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_ORDER_REPLIED.String(), fmt.Sprintf(format, args...))
}

func IsStorePermissionDenied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_STORE_PERMISSION_DENIED.String() && e.Code == 403
}

func ErrorStorePermissionDenied(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_STORE_PERMISSION_DENIED.String(), fmt.Sprintf(format, args...))
}

func IsAppealAlreadyApproved(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_APPEAL_ALREADY_APPROVED.String() && e.Code == 409
}

func ErrorAppealAlreadyApproved(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_APPEAL_ALREADY_APPROVED.String(), fmt.Sprintf(format, args...))
}
