// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: review/v1/review.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 评价信息
type ReviewInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	ServiceScore  int32                  `protobuf:"varint,5,opt,name=service_score,json=serviceScore,proto3" json:"service_score,omitempty"`
	ExpressScore  int32                  `protobuf:"varint,6,opt,name=express_score,json=expressScore,proto3" json:"express_score,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	PicInfo       string                 `protobuf:"bytes,8,opt,name=pic_info,json=picInfo,proto3" json:"pic_info,omitempty"`
	VideoInfo     string                 `protobuf:"bytes,9,opt,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewInfo) Reset() {
	*x = ReviewInfo{}
	mi := &file_review_v1_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewInfo) ProtoMessage() {}

func (x *ReviewInfo) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewInfo.ProtoReflect.Descriptor instead.
func (*ReviewInfo) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewInfo) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ReviewInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReviewInfo) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ReviewInfo) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ReviewInfo) GetServiceScore() int32 {
	if x != nil {
		return x.ServiceScore
	}
	return 0
}

func (x *ReviewInfo) GetExpressScore() int32 {
	if x != nil {
		return x.ExpressScore
	}
	return 0
}

func (x *ReviewInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReviewInfo) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *ReviewInfo) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

func (x *ReviewInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 创建评价
type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	ServiceScore  int32                  `protobuf:"varint,4,opt,name=service_score,json=serviceScore,proto3" json:"service_score,omitempty"`
	ExpressScore  int32                  `protobuf:"varint,5,opt,name=express_score,json=expressScore,proto3" json:"express_score,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	PicInfo       string                 `protobuf:"bytes,7,opt,name=pic_info,json=picInfo,proto3" json:"pic_info,omitempty"`
	VideoInfo     string                 `protobuf:"bytes,8,opt,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty"`
	Anonymous     bool                   `protobuf:"varint,9,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_review_v1_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReviewRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReviewRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateReviewRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CreateReviewRequest) GetServiceScore() int32 {
	if x != nil {
		return x.ServiceScore
	}
	return 0
}

func (x *CreateReviewRequest) GetExpressScore() int32 {
	if x != nil {
		return x.ExpressScore
	}
	return 0
}

func (x *CreateReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateReviewRequest) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *CreateReviewRequest) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

func (x *CreateReviewRequest) GetAnonymous() bool {
	if x != nil {
		return x.Anonymous
	}
	return false
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_review_v1_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReviewResponse) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

// 获取评价
type GetReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewRequest) Reset() {
	*x = GetReviewRequest{}
	mi := &file_review_v1_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewRequest) ProtoMessage() {}

func (x *GetReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewRequest.ProtoReflect.Descriptor instead.
func (*GetReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{3}
}

func (x *GetReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

type GetReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ReviewInfo            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewResponse) Reset() {
	*x = GetReviewResponse{}
	mi := &file_review_v1_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewResponse) ProtoMessage() {}

func (x *GetReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewResponse.ProtoReflect.Descriptor instead.
func (*GetReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{4}
}

func (x *GetReviewResponse) GetData() *ReviewInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 审核评价
type AuditReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	OpUser        string                 `protobuf:"bytes,3,opt,name=op_user,json=opUser,proto3" json:"op_user,omitempty"`
	OpReason      string                 `protobuf:"bytes,4,opt,name=op_reason,json=opReason,proto3" json:"op_reason,omitempty"`
	OpRemarks     *string                `protobuf:"bytes,5,opt,name=op_remarks,json=opRemarks,proto3,oneof" json:"op_remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditReviewRequest) Reset() {
	*x = AuditReviewRequest{}
	mi := &file_review_v1_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditReviewRequest) ProtoMessage() {}

func (x *AuditReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditReviewRequest.ProtoReflect.Descriptor instead.
func (*AuditReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{5}
}

func (x *AuditReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *AuditReviewRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuditReviewRequest) GetOpUser() string {
	if x != nil {
		return x.OpUser
	}
	return ""
}

func (x *AuditReviewRequest) GetOpReason() string {
	if x != nil {
		return x.OpReason
	}
	return ""
}

func (x *AuditReviewRequest) GetOpRemarks() string {
	if x != nil && x.OpRemarks != nil {
		return *x.OpRemarks
	}
	return ""
}

type AuditReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditReviewResponse) Reset() {
	*x = AuditReviewResponse{}
	mi := &file_review_v1_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditReviewResponse) ProtoMessage() {}

func (x *AuditReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditReviewResponse.ProtoReflect.Descriptor instead.
func (*AuditReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{6}
}

func (x *AuditReviewResponse) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *AuditReviewResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 回复评论
type ReplyReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	StoreId       int64                  `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	PicInfo       string                 `protobuf:"bytes,4,opt,name=pic_info,json=picInfo,proto3" json:"pic_info,omitempty"`
	VideoInfo     string                 `protobuf:"bytes,5,opt,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyReviewRequest) Reset() {
	*x = ReplyReviewRequest{}
	mi := &file_review_v1_review_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyReviewRequest) ProtoMessage() {}

func (x *ReplyReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyReviewRequest.ProtoReflect.Descriptor instead.
func (*ReplyReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{7}
}

func (x *ReplyReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *ReplyReviewRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *ReplyReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReplyReviewRequest) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *ReplyReviewRequest) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

type ReplyReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyId       int64                  `protobuf:"varint,1,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyReviewResponse) Reset() {
	*x = ReplyReviewResponse{}
	mi := &file_review_v1_review_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyReviewResponse) ProtoMessage() {}

func (x *ReplyReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyReviewResponse.ProtoReflect.Descriptor instead.
func (*ReplyReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{8}
}

func (x *ReplyReviewResponse) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

// 申诉评论
type AppealReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	StoreId       int64                  `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	PicInfo       string                 `protobuf:"bytes,5,opt,name=pic_info,json=picInfo,proto3" json:"pic_info,omitempty"`
	VideoInfo     string                 `protobuf:"bytes,6,opt,name=video_info,json=videoInfo,proto3" json:"video_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppealReviewRequest) Reset() {
	*x = AppealReviewRequest{}
	mi := &file_review_v1_review_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppealReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppealReviewRequest) ProtoMessage() {}

func (x *AppealReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppealReviewRequest.ProtoReflect.Descriptor instead.
func (*AppealReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{9}
}

func (x *AppealReviewRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *AppealReviewRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *AppealReviewRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AppealReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AppealReviewRequest) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *AppealReviewRequest) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

type AppealReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppealId      int64                  `protobuf:"varint,1,opt,name=appeal_id,json=appealId,proto3" json:"appeal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppealReviewResponse) Reset() {
	*x = AppealReviewResponse{}
	mi := &file_review_v1_review_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppealReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppealReviewResponse) ProtoMessage() {}

func (x *AppealReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppealReviewResponse.ProtoReflect.Descriptor instead.
func (*AppealReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{10}
}

func (x *AppealReviewResponse) GetAppealId() int64 {
	if x != nil {
		return x.AppealId
	}
	return 0
}

// 审核申诉
type AuditAppealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppealId      int64                  `protobuf:"varint,1,opt,name=appeal_id,json=appealId,proto3" json:"appeal_id,omitempty"`
	ReviewId      int64                  `protobuf:"varint,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	OpUser        string                 `protobuf:"bytes,4,opt,name=op_user,json=opUser,proto3" json:"op_user,omitempty"`
	OpReason      string                 `protobuf:"bytes,5,opt,name=op_reason,json=opReason,proto3" json:"op_reason,omitempty"`
	OpRemarks     *string                `protobuf:"bytes,6,opt,name=op_remarks,json=opRemarks,proto3,oneof" json:"op_remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAppealRequest) Reset() {
	*x = AuditAppealRequest{}
	mi := &file_review_v1_review_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAppealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAppealRequest) ProtoMessage() {}

func (x *AuditAppealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAppealRequest.ProtoReflect.Descriptor instead.
func (*AuditAppealRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{11}
}

func (x *AuditAppealRequest) GetAppealId() int64 {
	if x != nil {
		return x.AppealId
	}
	return 0
}

func (x *AuditAppealRequest) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *AuditAppealRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuditAppealRequest) GetOpUser() string {
	if x != nil {
		return x.OpUser
	}
	return ""
}

func (x *AuditAppealRequest) GetOpReason() string {
	if x != nil {
		return x.OpReason
	}
	return ""
}

func (x *AuditAppealRequest) GetOpRemarks() string {
	if x != nil && x.OpRemarks != nil {
		return *x.OpRemarks
	}
	return ""
}

type AuditAppealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAppealResponse) Reset() {
	*x = AuditAppealResponse{}
	mi := &file_review_v1_review_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAppealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAppealResponse) ProtoMessage() {}

func (x *AuditAppealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAppealResponse.ProtoReflect.Descriptor instead.
func (*AuditAppealResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{12}
}

// 获取用户评价列表
type ListReviewsByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsByUserIdRequest) Reset() {
	*x = ListReviewsByUserIdRequest{}
	mi := &file_review_v1_review_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsByUserIdRequest) ProtoMessage() {}

func (x *ListReviewsByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsByUserIdRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{13}
}

func (x *ListReviewsByUserIdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListReviewsByUserIdRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReviewsByUserIdRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListReviewsByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ReviewInfo          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsByUserIdResponse) Reset() {
	*x = ListReviewsByUserIdResponse{}
	mi := &file_review_v1_review_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsByUserIdResponse) ProtoMessage() {}

func (x *ListReviewsByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsByUserIdResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{14}
}

func (x *ListReviewsByUserIdResponse) GetList() []*ReviewInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 获取商家评价列表
type ListReviewsByStoreIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       int64                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsByStoreIdRequest) Reset() {
	*x = ListReviewsByStoreIdRequest{}
	mi := &file_review_v1_review_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsByStoreIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsByStoreIdRequest) ProtoMessage() {}

func (x *ListReviewsByStoreIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsByStoreIdRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsByStoreIdRequest) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{15}
}

func (x *ListReviewsByStoreIdRequest) GetStoreId() int64 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *ListReviewsByStoreIdRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReviewsByStoreIdRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListReviewsByStoreIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ReviewInfo          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsByStoreIdResponse) Reset() {
	*x = ListReviewsByStoreIdResponse{}
	mi := &file_review_v1_review_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsByStoreIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsByStoreIdResponse) ProtoMessage() {}

func (x *ListReviewsByStoreIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_review_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsByStoreIdResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsByStoreIdResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_review_proto_rawDescGZIP(), []int{16}
}

func (x *ListReviewsByStoreIdResponse) GetList() []*ReviewInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_review_v1_review_proto protoreflect.FileDescriptor

const file_review_v1_review_proto_rawDesc = "" +
	"\n" +
	"\x16review/v1/review.proto\x12\rapi.review.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xa9\x02\n" +
	"\n" +
	"ReviewInfo\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12#\n" +
	"\rservice_score\x18\x05 \x01(\x05R\fserviceScore\x12#\n" +
	"\rexpress_score\x18\x06 \x01(\x05R\fexpressScore\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x19\n" +
	"\bpic_info\x18\b \x01(\tR\apicInfo\x12\x1d\n" +
	"\n" +
	"video_info\x18\t \x01(\tR\tvideoInfo\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"\xec\x02\n" +
	"\x13CreateReviewRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\"\n" +
	"\border_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aorderId\x12%\n" +
	"\x05score\x18\x03 \x01(\x05B\x0f\xfaB\f\x1a\n" +
	"0\x010\x020\x030\x040\x05R\x05score\x124\n" +
	"\rservice_score\x18\x04 \x01(\x05B\x0f\xfaB\f\x1a\n" +
	"0\x010\x020\x030\x040\x05R\fserviceScore\x124\n" +
	"\rexpress_score\x18\x05 \x01(\x05B\x0f\xfaB\f\x1a\n" +
	"0\x010\x020\x030\x040\x05R\fexpressScore\x12$\n" +
	"\acontent\x18\x06 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\b\x18\xff\x01R\acontent\x12\x19\n" +
	"\bpic_info\x18\a \x01(\tR\apicInfo\x12\x1d\n" +
	"\n" +
	"video_info\x18\b \x01(\tR\tvideoInfo\x12\x1c\n" +
	"\tanonymous\x18\t \x01(\bR\tanonymous\"3\n" +
	"\x14CreateReviewResponse\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\"8\n" +
	"\x10GetReviewRequest\x12$\n" +
	"\treview_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewId\"B\n" +
	"\x11GetReviewResponse\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x19.api.review.v1.ReviewInfoR\x04data\"\xd6\x01\n" +
	"\x12AuditReviewRequest\x12$\n" +
	"\treview_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewId\x12\x1f\n" +
	"\x06status\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06status\x12 \n" +
	"\aop_user\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\x06opUser\x12$\n" +
	"\top_reason\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\bopReason\x12\"\n" +
	"\n" +
	"op_remarks\x18\x05 \x01(\tH\x00R\topRemarks\x88\x01\x01B\r\n" +
	"\v_op_remarks\"J\n" +
	"\x13AuditReviewResponse\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\xbe\x01\n" +
	"\x12ReplyReviewRequest\x12$\n" +
	"\treview_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewId\x12\"\n" +
	"\bstore_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\astoreId\x12$\n" +
	"\acontent\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\b\x18\xff\x01R\acontent\x12\x19\n" +
	"\bpic_info\x18\x04 \x01(\tR\apicInfo\x12\x1d\n" +
	"\n" +
	"video_info\x18\x05 \x01(\tR\tvideoInfo\"0\n" +
	"\x13ReplyReviewResponse\x12\x19\n" +
	"\breply_id\x18\x01 \x01(\x03R\areplyId\"\xe3\x01\n" +
	"\x13AppealReviewRequest\x12$\n" +
	"\treview_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewId\x12\"\n" +
	"\bstore_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\astoreId\x12\"\n" +
	"\x06reason\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\xc8\x01R\x06reason\x12$\n" +
	"\acontent\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\xc8\x01R\acontent\x12\x19\n" +
	"\bpic_info\x18\x05 \x01(\tR\apicInfo\x12\x1d\n" +
	"\n" +
	"video_info\x18\x06 \x01(\tR\tvideoInfo\"3\n" +
	"\x14AppealReviewResponse\x12\x1b\n" +
	"\tappeal_id\x18\x01 \x01(\x03R\bappealId\"\x85\x02\n" +
	"\x12AuditAppealRequest\x12$\n" +
	"\tappeal_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bappealId\x12$\n" +
	"\treview_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\breviewId\x12\x1f\n" +
	"\x06status\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06status\x12 \n" +
	"\aop_user\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\x06opUser\x12$\n" +
	"\top_reason\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\bopReason\x12+\n" +
	"\n" +
	"op_remarks\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x02H\x00R\topRemarks\x88\x01\x01B\r\n" +
	"\v_op_remarks\"\x15\n" +
	"\x13AuditAppealResponse\"x\n" +
	"\x1aListReviewsByUserIdRequest\x12 \n" +
	"\auser_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\x12\x1b\n" +
	"\x04page\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x04page\x12\x1b\n" +
	"\x04size\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x04size\"L\n" +
	"\x1bListReviewsByUserIdResponse\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.api.review.v1.ReviewInfoR\x04list\"{\n" +
	"\x1bListReviewsByStoreIdRequest\x12\"\n" +
	"\bstore_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\astoreId\x12\x1b\n" +
	"\x04page\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x04page\x12\x1b\n" +
	"\x04size\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x04size\"M\n" +
	"\x1cListReviewsByStoreIdResponse\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.api.review.v1.ReviewInfoR\x04list2\xd8\a\n" +
	"\x06Review\x12n\n" +
	"\fCreateReview\x12\".api.review.v1.CreateReviewRequest\x1a#.api.review.v1.CreateReviewResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/review\x12n\n" +
	"\tGetReview\x12\x1f.api.review.v1.GetReviewRequest\x1a .api.review.v1.GetReviewResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/review/{review_id}\x12q\n" +
	"\vAuditReview\x12!.api.review.v1.AuditReviewRequest\x1a\".api.review.v1.AuditReviewResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/review/audit\x12q\n" +
	"\vReplyReview\x12!.api.review.v1.ReplyReviewRequest\x1a\".api.review.v1.ReplyReviewResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/review/reply\x12u\n" +
	"\fAppealReview\x12\".api.review.v1.AppealReviewRequest\x1a#.api.review.v1.AppealReviewResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/review/appeal\x12q\n" +
	"\vAuditAppeal\x12!.api.review.v1.AuditAppealRequest\x1a\".api.review.v1.AuditAppealResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/appeal/audit\x12\x8b\x01\n" +
	"\x13ListReviewsByUserId\x12).api.review.v1.ListReviewsByUserIdRequest\x1a*.api.review.v1.ListReviewsByUserIdResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/{user_id}/reviews\x12\x8f\x01\n" +
	"\x14ListReviewsByStoreId\x12*.api.review.v1.ListReviewsByStoreIdRequest\x1a+.api.review.v1.ListReviewsByStoreIdResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/{store_id}/reviewsB2\n" +
	"\rapi.review.v1P\x01Z\x1freview-service/api/review/v1;v1b\x06proto3"

var (
	file_review_v1_review_proto_rawDescOnce sync.Once
	file_review_v1_review_proto_rawDescData []byte
)

func file_review_v1_review_proto_rawDescGZIP() []byte {
	file_review_v1_review_proto_rawDescOnce.Do(func() {
		file_review_v1_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_v1_review_proto_rawDesc), len(file_review_v1_review_proto_rawDesc)))
	})
	return file_review_v1_review_proto_rawDescData
}

var file_review_v1_review_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_review_v1_review_proto_goTypes = []any{
	(*ReviewInfo)(nil),                   // 0: api.review.v1.ReviewInfo
	(*CreateReviewRequest)(nil),          // 1: api.review.v1.CreateReviewRequest
	(*CreateReviewResponse)(nil),         // 2: api.review.v1.CreateReviewResponse
	(*GetReviewRequest)(nil),             // 3: api.review.v1.GetReviewRequest
	(*GetReviewResponse)(nil),            // 4: api.review.v1.GetReviewResponse
	(*AuditReviewRequest)(nil),           // 5: api.review.v1.AuditReviewRequest
	(*AuditReviewResponse)(nil),          // 6: api.review.v1.AuditReviewResponse
	(*ReplyReviewRequest)(nil),           // 7: api.review.v1.ReplyReviewRequest
	(*ReplyReviewResponse)(nil),          // 8: api.review.v1.ReplyReviewResponse
	(*AppealReviewRequest)(nil),          // 9: api.review.v1.AppealReviewRequest
	(*AppealReviewResponse)(nil),         // 10: api.review.v1.AppealReviewResponse
	(*AuditAppealRequest)(nil),           // 11: api.review.v1.AuditAppealRequest
	(*AuditAppealResponse)(nil),          // 12: api.review.v1.AuditAppealResponse
	(*ListReviewsByUserIdRequest)(nil),   // 13: api.review.v1.ListReviewsByUserIdRequest
	(*ListReviewsByUserIdResponse)(nil),  // 14: api.review.v1.ListReviewsByUserIdResponse
	(*ListReviewsByStoreIdRequest)(nil),  // 15: api.review.v1.ListReviewsByStoreIdRequest
	(*ListReviewsByStoreIdResponse)(nil), // 16: api.review.v1.ListReviewsByStoreIdResponse
}
var file_review_v1_review_proto_depIdxs = []int32{
	0,  // 0: api.review.v1.GetReviewResponse.data:type_name -> api.review.v1.ReviewInfo
	0,  // 1: api.review.v1.ListReviewsByUserIdResponse.list:type_name -> api.review.v1.ReviewInfo
	0,  // 2: api.review.v1.ListReviewsByStoreIdResponse.list:type_name -> api.review.v1.ReviewInfo
	1,  // 3: api.review.v1.Review.CreateReview:input_type -> api.review.v1.CreateReviewRequest
	3,  // 4: api.review.v1.Review.GetReview:input_type -> api.review.v1.GetReviewRequest
	5,  // 5: api.review.v1.Review.AuditReview:input_type -> api.review.v1.AuditReviewRequest
	7,  // 6: api.review.v1.Review.ReplyReview:input_type -> api.review.v1.ReplyReviewRequest
	9,  // 7: api.review.v1.Review.AppealReview:input_type -> api.review.v1.AppealReviewRequest
	11, // 8: api.review.v1.Review.AuditAppeal:input_type -> api.review.v1.AuditAppealRequest
	13, // 9: api.review.v1.Review.ListReviewsByUserId:input_type -> api.review.v1.ListReviewsByUserIdRequest
	15, // 10: api.review.v1.Review.ListReviewsByStoreId:input_type -> api.review.v1.ListReviewsByStoreIdRequest
	2,  // 11: api.review.v1.Review.CreateReview:output_type -> api.review.v1.CreateReviewResponse
	4,  // 12: api.review.v1.Review.GetReview:output_type -> api.review.v1.GetReviewResponse
	6,  // 13: api.review.v1.Review.AuditReview:output_type -> api.review.v1.AuditReviewResponse
	8,  // 14: api.review.v1.Review.ReplyReview:output_type -> api.review.v1.ReplyReviewResponse
	10, // 15: api.review.v1.Review.AppealReview:output_type -> api.review.v1.AppealReviewResponse
	12, // 16: api.review.v1.Review.AuditAppeal:output_type -> api.review.v1.AuditAppealResponse
	14, // 17: api.review.v1.Review.ListReviewsByUserId:output_type -> api.review.v1.ListReviewsByUserIdResponse
	16, // 18: api.review.v1.Review.ListReviewsByStoreId:output_type -> api.review.v1.ListReviewsByStoreIdResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_review_v1_review_proto_init() }
func file_review_v1_review_proto_init() {
	if File_review_v1_review_proto != nil {
		return
	}
	file_review_v1_review_proto_msgTypes[5].OneofWrappers = []any{}
	file_review_v1_review_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_v1_review_proto_rawDesc), len(file_review_v1_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_v1_review_proto_goTypes,
		DependencyIndexes: file_review_v1_review_proto_depIdxs,
		MessageInfos:      file_review_v1_review_proto_msgTypes,
	}.Build()
	File_review_v1_review_proto = out.File
	file_review_v1_review_proto_goTypes = nil
	file_review_v1_review_proto_depIdxs = nil
}
